.head on
.mode csv
.out overall_clusters.csv
SELECT 
  count(CASE WHEN hotel_cluster = 0 THEN 1 ELSE NULL END) as c0,
  count(CASE WHEN hotel_cluster = 1 THEN 1 ELSE NULL END) as c1,
  count(CASE WHEN hotel_cluster = 2 THEN 1 ELSE NULL END) as c2,
  count(CASE WHEN hotel_cluster = 3 THEN 1 ELSE NULL END) as c3,
  count(CASE WHEN hotel_cluster = 4 THEN 1 ELSE NULL END) as c4,
  count(CASE WHEN hotel_cluster = 5 THEN 1 ELSE NULL END) as c5,
  count(CASE WHEN hotel_cluster = 6 THEN 1 ELSE NULL END) as c6,
  count(CASE WHEN hotel_cluster = 7 THEN 1 ELSE NULL END) as c7,
  count(CASE WHEN hotel_cluster = 8 THEN 1 ELSE NULL END) as c8,
  count(CASE WHEN hotel_cluster = 9 THEN 1 ELSE NULL END) as c9,

  count(CASE WHEN hotel_cluster = 10 THEN 1 ELSE NULL END) as c10,
  count(CASE WHEN hotel_cluster = 11 THEN 1 ELSE NULL END) as c11,
  count(CASE WHEN hotel_cluster = 12 THEN 1 ELSE NULL END) as c12,
  count(CASE WHEN hotel_cluster = 13 THEN 1 ELSE NULL END) as c13,
  count(CASE WHEN hotel_cluster = 14 THEN 1 ELSE NULL END) as c14,
  count(CASE WHEN hotel_cluster = 15 THEN 1 ELSE NULL END) as c15,
  count(CASE WHEN hotel_cluster = 16 THEN 1 ELSE NULL END) as c16,
  count(CASE WHEN hotel_cluster = 17 THEN 1 ELSE NULL END) as c17,
  count(CASE WHEN hotel_cluster = 18 THEN 1 ELSE NULL END) as c18,
  count(CASE WHEN hotel_cluster = 19 THEN 1 ELSE NULL END) as c19,

  count(CASE WHEN hotel_cluster = 20 THEN 1 ELSE NULL END) as c20,
  count(CASE WHEN hotel_cluster = 21 THEN 1 ELSE NULL END) as c21,
  count(CASE WHEN hotel_cluster = 22 THEN 1 ELSE NULL END) as c22,
  count(CASE WHEN hotel_cluster = 23 THEN 1 ELSE NULL END) as c23,
  count(CASE WHEN hotel_cluster = 24 THEN 1 ELSE NULL END) as c24,
  count(CASE WHEN hotel_cluster = 25 THEN 1 ELSE NULL END) as c25,
  count(CASE WHEN hotel_cluster = 26 THEN 1 ELSE NULL END) as c26,
  count(CASE WHEN hotel_cluster = 27 THEN 1 ELSE NULL END) as c27,
  count(CASE WHEN hotel_cluster = 28 THEN 1 ELSE NULL END) as c28,
  count(CASE WHEN hotel_cluster = 29 THEN 1 ELSE NULL END) as c29,

  count(CASE WHEN hotel_cluster = 30 THEN 1 ELSE NULL END) as c30,
  count(CASE WHEN hotel_cluster = 31 THEN 1 ELSE NULL END) as c31,
  count(CASE WHEN hotel_cluster = 32 THEN 1 ELSE NULL END) as c32,
  count(CASE WHEN hotel_cluster = 33 THEN 1 ELSE NULL END) as c33,
  count(CASE WHEN hotel_cluster = 34 THEN 1 ELSE NULL END) as c34,
  count(CASE WHEN hotel_cluster = 35 THEN 1 ELSE NULL END) as c35,
  count(CASE WHEN hotel_cluster = 36 THEN 1 ELSE NULL END) as c36,
  count(CASE WHEN hotel_cluster = 37 THEN 1 ELSE NULL END) as c37,
  count(CASE WHEN hotel_cluster = 38 THEN 1 ELSE NULL END) as c38,
  count(CASE WHEN hotel_cluster = 39 THEN 1 ELSE NULL END) as c39,

  count(CASE WHEN hotel_cluster = 40 THEN 1 ELSE NULL END) as c40,
  count(CASE WHEN hotel_cluster = 41 THEN 1 ELSE NULL END) as c41,
  count(CASE WHEN hotel_cluster = 42 THEN 1 ELSE NULL END) as c42,
  count(CASE WHEN hotel_cluster = 43 THEN 1 ELSE NULL END) as c43,
  count(CASE WHEN hotel_cluster = 44 THEN 1 ELSE NULL END) as c44,
  count(CASE WHEN hotel_cluster = 45 THEN 1 ELSE NULL END) as c45,
  count(CASE WHEN hotel_cluster = 46 THEN 1 ELSE NULL END) as c46,
  count(CASE WHEN hotel_cluster = 47 THEN 1 ELSE NULL END) as c47,
  count(CASE WHEN hotel_cluster = 48 THEN 1 ELSE NULL END) as c48,
  count(CASE WHEN hotel_cluster = 49 THEN 1 ELSE NULL END) as c49,

  count(CASE WHEN hotel_cluster = 50 THEN 1 ELSE NULL END) as c50,
  count(CASE WHEN hotel_cluster = 51 THEN 1 ELSE NULL END) as c51,
  count(CASE WHEN hotel_cluster = 52 THEN 1 ELSE NULL END) as c52,
  count(CASE WHEN hotel_cluster = 53 THEN 1 ELSE NULL END) as c53,
  count(CASE WHEN hotel_cluster = 54 THEN 1 ELSE NULL END) as c54,
  count(CASE WHEN hotel_cluster = 55 THEN 1 ELSE NULL END) as c55,
  count(CASE WHEN hotel_cluster = 56 THEN 1 ELSE NULL END) as c56,
  count(CASE WHEN hotel_cluster = 57 THEN 1 ELSE NULL END) as c57,
  count(CASE WHEN hotel_cluster = 58 THEN 1 ELSE NULL END) as c58,
  count(CASE WHEN hotel_cluster = 59 THEN 1 ELSE NULL END) as c59,

  count(CASE WHEN hotel_cluster = 60 THEN 1 ELSE NULL END) as c60,
  count(CASE WHEN hotel_cluster = 61 THEN 1 ELSE NULL END) as c61,
  count(CASE WHEN hotel_cluster = 62 THEN 1 ELSE NULL END) as c62,
  count(CASE WHEN hotel_cluster = 63 THEN 1 ELSE NULL END) as c63,
  count(CASE WHEN hotel_cluster = 64 THEN 1 ELSE NULL END) as c64,
  count(CASE WHEN hotel_cluster = 65 THEN 1 ELSE NULL END) as c65,
  count(CASE WHEN hotel_cluster = 66 THEN 1 ELSE NULL END) as c66,
  count(CASE WHEN hotel_cluster = 67 THEN 1 ELSE NULL END) as c67,
  count(CASE WHEN hotel_cluster = 68 THEN 1 ELSE NULL END) as c68,
  count(CASE WHEN hotel_cluster = 69 THEN 1 ELSE NULL END) as c69,

  count(CASE WHEN hotel_cluster = 70 THEN 1 ELSE NULL END) as c70,
  count(CASE WHEN hotel_cluster = 71 THEN 1 ELSE NULL END) as c71,
  count(CASE WHEN hotel_cluster = 72 THEN 1 ELSE NULL END) as c72,
  count(CASE WHEN hotel_cluster = 73 THEN 1 ELSE NULL END) as c73,
  count(CASE WHEN hotel_cluster = 74 THEN 1 ELSE NULL END) as c74,
  count(CASE WHEN hotel_cluster = 75 THEN 1 ELSE NULL END) as c75,
  count(CASE WHEN hotel_cluster = 76 THEN 1 ELSE NULL END) as c76,
  count(CASE WHEN hotel_cluster = 77 THEN 1 ELSE NULL END) as c77,
  count(CASE WHEN hotel_cluster = 78 THEN 1 ELSE NULL END) as c78,
  count(CASE WHEN hotel_cluster = 79 THEN 1 ELSE NULL END) as c79,

  count(CASE WHEN hotel_cluster = 80 THEN 1 ELSE NULL END) as c80,
  count(CASE WHEN hotel_cluster = 81 THEN 1 ELSE NULL END) as c81,
  count(CASE WHEN hotel_cluster = 82 THEN 1 ELSE NULL END) as c82,
  count(CASE WHEN hotel_cluster = 83 THEN 1 ELSE NULL END) as c83,
  count(CASE WHEN hotel_cluster = 84 THEN 1 ELSE NULL END) as c84,
  count(CASE WHEN hotel_cluster = 85 THEN 1 ELSE NULL END) as c85,
  count(CASE WHEN hotel_cluster = 86 THEN 1 ELSE NULL END) as c86,
  count(CASE WHEN hotel_cluster = 87 THEN 1 ELSE NULL END) as c87,
  count(CASE WHEN hotel_cluster = 88 THEN 1 ELSE NULL END) as c88,
  count(CASE WHEN hotel_cluster = 89 THEN 1 ELSE NULL END) as c89,

  count(CASE WHEN hotel_cluster = 90 THEN 1 ELSE NULL END) as c90,
  count(CASE WHEN hotel_cluster = 91 THEN 1 ELSE NULL END) as c91,
  count(CASE WHEN hotel_cluster = 92 THEN 1 ELSE NULL END) as c92,
  count(CASE WHEN hotel_cluster = 93 THEN 1 ELSE NULL END) as c93,
  count(CASE WHEN hotel_cluster = 94 THEN 1 ELSE NULL END) as c94,
  count(CASE WHEN hotel_cluster = 95 THEN 1 ELSE NULL END) as c95,
  count(CASE WHEN hotel_cluster = 96 THEN 1 ELSE NULL END) as c96,
  count(CASE WHEN hotel_cluster = 97 THEN 1 ELSE NULL END) as c97,
  count(CASE WHEN hotel_cluster = 98 THEN 1 ELSE NULL END) as c98,
  count(CASE WHEN hotel_cluster = 99 THEN 1 ELSE NULL END) as c99
FROM train
WHERE is_booking = 1;


